#!/usr/bin/env python3
"""Genera docs/clasico-declaraciones.xlsx con todas las citas verificadas."""
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill, Border, Side
from openpyxl.utils import get_column_letter
from pathlib import Path

# ============================================================================
# DATOS
# ============================================================================

# Cada fila: (fecha, era, protagonista, cita, fuente, edicion, pagina, tipo, verificado, notas)

ROWS = [
    # ============ HEMEROTECA ABC VERIFICADAS (las joyas) ============
    ("1943-06-15", "El 11-1 (1943)", "ABC Madrid",
     "(Portada dedicada a 'SOLEMNES ACTOS RELIGIOSOS EN TOLEDO' — el 11-1 NO aparece)",
     "ABC", "ABC Madrid 15/06/1943", "Portada",
     "Hemeroteca digital ABC", "Sí",
     "Hallazgo: ABC NO destacó el 11-1 en portada dos días después del partido."),
    ("1943-06-16", "El 11-1 (1943)", "ABC Madrid",
     "(Portada dedicada a 'EL MINISTRO DE AGRICULTURA, EN GALICIA' — el 11-1 NO aparece)",
     "ABC", "ABC Madrid 16/06/1943", "Portada",
     "Hemeroteca digital ABC", "Sí",
     "Hallazgo: ABC tampoco destacó el 11-1 en portada el lunes."),
    ("1974-02-19", "Cruyff 0-5 al Bernabéu", "ABC Madrid",
     "Pasará la mala racha. Un Barcelona deslumbrante, articulado por ese genio del fútbol que es Joan Cruyff, goleó al Real Madrid en el Estadio Bernabéu. Unimos el aplauso sin reservas al gran Club azulgrana con el estímulo para que directivos, técnicos y jugadores del Madrid no pierdan la moral y superen el bache que hoy afecta al que durante muchos años fue el indiscutible mejor equipo del mundo. La hinchada madridista, una de las más deportivas y tenaces de España, debe apoyar ahora con más entusiasmo que nunca al histórico Club blanco.",
     "ABC", "ABC Madrid 19/02/1974", "Portada (pie de foto)",
     "Hemeroteca digital ABC", "Sí",
     "ABC (madridista) reconoce 'sin reservas' la genialidad de Cruyff."),
    ("1983-09-25", "Goikoetxea-Maradona", "ABC Madrid",
     "(Portada dedicada a 'EL GOBIERNO SOCIALISTA TOPA CON LA IGLESIA' — la lesión NO aparece)",
     "ABC", "ABC Madrid 25/09/1983", "Portada",
     "Hemeroteca digital ABC", "Sí",
     "Hallazgo: ABC NO destacó la patada de Goikoetxea a Maradona en portada."),
    ("1983-09-26", "Goikoetxea-Maradona", "ABC Madrid",
     "(Portada 'NUEVOS POBRES' — la lesión NO aparece)",
     "ABC", "ABC Madrid 26/09/1983", "Portada",
     "Hemeroteca digital ABC", "Sí",
     "Hallazgo: tampoco destacó al lunes siguiente."),
    ("1994-01-09", "Manita Dream Team", "ABC Madrid",
     "5-0: GOLEADA HISTÓRICA DEL BARCELONA AL REAL MADRID EN EL NOU CAMP",
     "ABC", "ABC Madrid 09/01/1994", "Portada (Sección Deportes)",
     "Hemeroteca digital ABC", "Sí",
     "Triplete de Romario, gol de Koeman e Iván Iglesias. Cruyff entrenador."),
    ("1995-01-08", "Venganza 5-0 (1995)", "ABC Madrid",
     "5-0: HISTÓRICA GOLEADA DEL REAL MADRID AL BARCELONA. El Real Madrid se impuso ayer al [Barcelona] por un resultado (5-0) que ya ha entrado en la historia del club de Chamartín, en un intenso partido que había despertado una inusitada expectación. El equipo blanco, arropado por más de cien mil personas que abarrotaron el Bernabéu, arrolló a su rival con una goleada que pudo ser aun mayor. El madridista Zamorano se convirtió en el héroe del partido al anotar tres tantos. Toda España estuvo pendiente del choque entre dos de los más grandes clubes mundiales, que ofrecieron un gran espectáculo presidido por la deportividad, sólo empañada por una aislada acción de Stoichkov.",
     "ABC", "ABC Madrid 08/01/1995", "Portada",
     "Hemeroteca digital ABC", "Sí",
     "365 días después de la manita. Triplete de Zamorano. Stoichkov expulsado."),
    ("2002-11-24", "Cochinillo a Figo", "Joan Gaspart (presidente FC Barcelona)",
     "El público reaccionó ante una provocación. (Recogido por ABC) Violencia en las gradas del Camp Nou en un partido que empató el Madrid (0-0). El árbitro suspendió el encuentro durante quince minutos por el lanzamiento masivo de objetos a Luis Figo.",
     "ABC", "ABC Madrid 24/11/2002", "Portada (también pp 112-116)",
     "Hemeroteca digital ABC", "Sí",
     "Foto: 'Luis Figo en el momento de sacar un córner custodiado por la Policía' (foto: Ignacio Gil)."),
    ("2002-11-25", "Cochinillo a Figo", "ABC Madrid",
     "Según el Reglamento, el Camp Nou debería ser clausurado. La infracción grave prevé una sanción de uno a tres partidos; la muy grave, de cuatro a una temporada.",
     "ABC", "ABC Madrid 25/11/2002", "Portada (también pp 92-94)",
     "Hemeroteca digital ABC", "Sí",
     "Editorial pidiendo la clausura del Camp Nou."),
    ("2005-11-20", "Ronaldinho ovación Bernabéu", "ABC Madrid",
     "Un gran Barça le pasa por encima al Real Madrid. El Bernabéu se rinde al Balón de Oro. Ronaldinho, autor de dos de los tres goles de su equipo, recibió la ovación de los espectadores tras marcar el 0-3 definitivo.",
     "ABC", "ABC Madrid 20/11/2005", "Portada (pp 89-93)",
     "Hemeroteca digital ABC", "Sí",
     "Foto: 'Ronaldinho fue el gran protagonista del partido. En la imagen, se escapa del marcaje de Sergio Ramos' (foto: Ignacio Gil)."),
    ("2009-05-03", "2-6 Pep primer año", "ABC Madrid",
     "El Barça sentencia la Liga. Histórica goleada (2-6) de los azulgrana, que se exhibieron ante un débil Real Madrid. El gesto de decepción de Casillas resume el sentimiento del madridismo al ver cómo vuela el título.",
     "ABC", "ABC Madrid 03/05/2009", "Portada (pp 88+)",
     "Hemeroteca digital ABC", "Sí",
     "ABC reconoce 'un débil Real Madrid'."),
    ("2010-11-30", "Manita a Mou (5-0)", "ABC Madrid",
     "BARÇA-REAL MADRID. Guardiola humilla a Mourinho. La estrategia del Barça en el derbi ante el Real Madrid se resolvió con una lección táctica de Pep Guardiola sobre Mourinho, que coloca líderes a los azulgrana. 5-0",
     "ABC", "ABC Madrid 30/11/2010", "Portada (Deportes 6-7 y 68-77)",
     "Hemeroteca digital ABC", "Sí",
     "Periódico afín al Madrid titula 'Guardiola humilla a Mourinho'."),
    ("2010-11-30", "Manita a Mou (5-0)", "Marca (titular hoy)",
     "Mouchísimo Barça.",
     "Marca (web)", "Marca 30/11/2010", "Portada digital",
     "Wayback Machine (archive.org)", "Sí",
     "Snap 30/11/2010 12:12 UTC."),
    ("2010-11-30", "Manita a Mou (5-0)", "Marca",
     "Barcelona 5-0 Real Madrid. Goleada histórica. Este Barça es una máquina.",
     "Marca (web)", "Marca 30/11/2010", "Portada digital",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2010-11-30", "Manita a Mou (5-0)", "José Mourinho (recogido por Marca)",
     "Cuando te meten 5 no se llora. Uno ha jugado al máximo nivel y otro muy mal. Es una derrota, no una humillación.",
     "Marca (web)", "Marca 30/11/2010", "RP post-partido",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2010-11-30", "Manita a Mou (5-0)", "José Mourinho (recogido por Marca)",
     "La semana pasada teníamos un punto más y hoy dos menos. Siempre he dicho que el Barça es un producto acabado y al Madrid le falta mucho.",
     "Marca (web)", "Marca 30/11/2010", "RP post-partido",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2010-11-30", "Manita a Mou (5-0)", "Pep Guardiola (recogido por Marca)",
     "No es verdad que seamos mucho mejores que el Real Madrid. Más que con el resultado, me quedo con cómo lo que hemos logrado.",
     "Marca (web)", "Marca 30/11/2010", "RP post-partido",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2010-11-30", "Manita a Mou (5-0)", "David Villa (recogido por Marca)",
     "Es el triunfo de un estilo. Para ser mi primer Clásico, más no puedo pedir. Estoy muy contento no sólo por el resultado, sino por la forma en que lo hemos logrado.",
     "Marca (web)", "Marca 30/11/2010", "Sala mixta",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2010-11-30", "Manita a Mou (5-0)", "Andrés Iniesta (recogido por Marca)",
     "Nos lo merecimos.",
     "Marca (web)", "Marca 30/11/2010", "Sala mixta",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2010-11-30", "Manita a Mou (5-0)", "Carles Puyol (recogido por Marca)",
     "Ha sido espectacular.",
     "Marca (web)", "Marca 30/11/2010", "Sala mixta",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2010-11-30", "Manita a Mou (5-0)", "Sport (titular)",
     "El Barça humilla al Madrid de Mourinho con otra 'manita' histórica. 'Orgasmo' culé en el Camp Nou.",
     "Sport (web)", "Sport 30/11/2010", "Portada digital",
     "Wayback Machine (archive.org)", "Sí",
     "Snap 30/11/2010 01:01 UTC."),
    ("2010-11-30", "Manita a Mou (5-0)", "Pep Guardiola (recogido por Sport)",
     "Es una victoria de todos los que han creído en el modelo.",
     "Sport (web)", "Sport 30/11/2010", "RP post-partido",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2010-11-30", "Manita a Mou (5-0)", "Carles Puyol (recogido por Sport)",
     "Ha sido el partido soñado.",
     "Sport (web)", "Sport 30/11/2010", "Zona mixta",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2010-11-30", "Manita a Mou (5-0)", "Andrés Iniesta (recogido por Sport)",
     "No hemos dejado hacer nada al Madrid.",
     "Sport (web)", "Sport 30/11/2010", "Zona mixta",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2010-11-30", "Manita a Mou (5-0)", "Jorge Valdano (recogido por Sport)",
     "El Barça ha sido muy, muy superior. Todos juntos saldremos de esta frustración.",
     "Sport (web)", "Sport 30/11/2010", "Declaraciones",
     "Wayback Machine (archive.org)", "Sí",
     "Director deportivo del Madrid asumiendo la derrota."),
    ("2010-12-02", "Manita a Mou (5-0)", "Sergio Ramos (a El País)",
     "Ya he pedido perdón a Puyol y Xavi. Al ser yo, todo el mundo lo exagera.",
     "El País (web)", "El País 02/12/2010", "Sección Deportes",
     "Wayback Machine (archive.org)", "Sí",
     "Sobre la entrada a Messi y la trifulca con Puyol."),
    ("2010-12-02", "Manita a Mou (5-0)", "Xavi Hernández (a El País)",
     "El 2-6 fue perfecto, pero el 5-0 lo supera. Tuve una sensación de enorme superioridad.",
     "El País (web)", "El País 02/12/2010", "Sección Deportes",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2009-05-04", "2-6 Pep primer año", "Marca (titular)",
     "Real Madrid 2-6 Barcelona. Humillación para sentenciar la Liga.",
     "Marca (web)", "Marca 04/05/2009", "Portada digital",
     "Wayback Machine (archive.org)", "Sí",
     "Snap 04/05/2009 06:24 UTC."),
    ("2009-05-04", "2-6 Pep primer año", "Luis Enrique (entrenador filial Barça)",
     "Fue un orgasmo futbolístico. ¡Qué maravilla ser aficionado del Barcelona y culé anoche!",
     "Marca (web)", "Marca 04/05/2009", "Declaraciones",
     "Wayback Machine (archive.org)", "Sí",
     "Luis Enrique entonces entrenaba el Barça B."),
    ("2009-05-04", "2-6 Pep primer año", "Iker Casillas (recogido por Marca)",
     "Nos ha pasado un rodillo por encima.",
     "Marca (web)", "Marca 04/05/2009", "Declaraciones",
     "Wayback Machine (archive.org)", "Sí",
     "Capitán del Real Madrid tras la goleada."),
    ("2009-05-04", "2-6 Pep primer año", "Raúl González (recogido por Marca)",
     "Te da impotencia ver que están cómodos y disfrutando.",
     "Marca (web)", "Marca 04/05/2009", "Declaraciones",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2009-05-04", "2-6 Pep primer año", "Txiki Begiristain (recogido por Marca)",
     "El Bernabéu es el mejor escenario para cerrar una Liga.",
     "Marca (web)", "Marca 04/05/2009", "Declaraciones",
     "Wayback Machine (archive.org)", "Sí",
     "Director deportivo del Barça."),
    ("2009-04-30", "Previa 2-6", "Lionel Messi (titular en Marca)",
     "Prefiero ganar al Chelsea que al Madrid.",
     "Marca (web)", "Marca 30/04/2009", "Portada digital",
     "Wayback Machine (archive.org)", "Sí",
     "Hoy en Marca."),
    ("2009-04-30", "Previa 2-6", "Raúl González (RP previa Madrid)",
     "En el Bernabéu, el favorito es el Madrid.",
     "Marca (web)", "Marca 30/04/2009", "RP previa",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2010-12-02", "Manita a Mou (5-0)", "Juan Mata (a El País)",
     "Espero que no paguemos los platos rotos.",
     "El País (web)", "El País 02/12/2010", "Sección Deportes",
     "Wayback Machine (archive.org)", "Sí",
     "Jugador del Valencia antes de visitar al Madrid el siguiente sábado."),
    ("2011-04-27", "RP del 'puto jefe'", "ABC Madrid",
     "Choque antes de la batalla final. Mourinho y Guardiola protagonizaron su primer rifirrafe la víspera de la semifinal de la Champions.",
     "ABC", "ABC Madrid 27/04/2011", "Portada (Deportes 74-77)",
     "Hemeroteca digital ABC", "Sí",
     "Mismo día de la rueda de prensa donde Pep dijo 'él es el puto jefe'."),
    ("2011-04-27", "RP del 'puto jefe'", "Mundo Deportivo (titular)",
     "Mourinho es el 'puto' jefe.",
     "Mundo Deportivo (web)", "MD 27/04/2011", "Portada digital",
     "Wayback Machine (archive.org)", "Sí",
     "Snapshot 27/04/2011 06:21 UTC. Titular literal en portada."),
    ("2011-04-27", "RP del 'puto jefe'", "Pep Guardiola (recogido por Mundo Deportivo)",
     "¿He respondido cuando ha dicho que no he respetado a un árbitro cuando en toda mi carrera los he respetado?",
     "Mundo Deportivo (web)", "MD 27/04/2011", "Portada digital",
     "Wayback Machine (archive.org)", "Sí",
     "Cita textual de Pep Guardiola en la rueda de prensa."),
    ("2011-04-27", "RP del 'puto jefe'", "Marca (titular)",
     "PEP GUARDIOLA RETA ANTE LA PRENSA A JOSÉ MOURINHO: 'A las 20.45 nos vemos en el campo'.",
     "Marca (web)", "Marca 27/04/2011", "Portada digital",
     "Wayback Machine (archive.org)", "Sí",
     "Snapshot 27/04/2011 08:44 UTC."),
    ("2011-04-27", "RP del 'puto jefe'", "Marca (cuerpo del artículo)",
     "Tras la comparecencia del entrenador del Real Madrid, se generó una enorme expectación por ver la respuesta de Pep Guardiola. Y no defraudó a nadie. Aceptó el desafío y contestó al preparador portugués como nunca había hecho.",
     "Marca (web)", "Marca 27/04/2011", "Crónica RP",
     "Wayback Machine (archive.org)", "Sí",
     "Marca, afín al Madrid, dice que Pep contestó 'como nunca había hecho'."),
    ("2011-04-27", "RP del 'puto jefe'", "Mundo Deportivo (titular Pepe)",
     "Pepe ya es un monumento al anti-fútbol. Aspira a consolidarse como violento número uno.",
     "Mundo Deportivo (web)", "MD 27/04/2011", "Portada digital",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2011-04-24", "Pre-Clásicos 2011", "AS (titular)",
     "Pepe, el coco del Barça.",
     "AS (web)", "AS 24/04/2011", "Portada digital",
     "Wayback Machine (archive.org)", "Sí",
     "AS prepara el Clásico anticipando a Pepe como referente del Madrid."),
    ("2011-04-28", "0-2 Champions, roja Pepe, UNICEF", "ABC Madrid",
     "Mou, expulsado. Messi pesca en medio de la bronca (0-2) y obliga al Real Madrid a una proeza en el Camp Nou.",
     "ABC", "ABC Madrid 28/04/2011", "Portada (Deportes 70-76)",
     "Hemeroteca digital ABC", "Sí",
     "Mismo día de la rajada de Mou con UNICEF y 'Champions vergonzosa'."),
    ("2011-04-29", "0-2 Champions, denuncias", "ABC Madrid",
     "Madrid y Barcelona cruzan denuncias ante la UEFA",
     "ABC", "ABC Madrid 29/04/2011", "Portada (pp 92-94)",
     "Hemeroteca digital ABC", "Sí", ""),
    ("2011-08-18", "Dedo en el ojo a Tito", "ABC Madrid",
     "Un Madrid con garra no evita el primer título del Barcelona (sólo en pie). Portada eclipsada por la JMJ del Papa.",
     "ABC", "ABC Madrid 18/08/2011", "Portada (página 62)",
     "Hemeroteca digital ABC", "Sí",
     "Hallazgo: el dedo en el ojo NO llegó a portada — ese día llegaba Benedicto XVI a Madrid para la JMJ."),
    ("2015-11-22", "Iniesta ovación Bernabéu", "ABC Madrid",
     "SONORO MINUTO DE SILENCIO CONTRA EL TERRORISMO. El Real Madrid-Barcelona (0-4) se jugó con normalidad entre medidas de seguridad inéditas. Una gran bandera de Francia fue desplegada ayer en el Bernabéu a los acordes de La Marsellesa en homenaje a las víctimas de los atentados de París. Rajoy acudió al Bernabéu.",
     "ABC", "ABC Madrid 22/11/2015", "Portada",
     "Hemeroteca digital ABC", "Sí",
     "Hallazgo: ovación a Iniesta eclipsada por los atentados de París (8 días antes)."),
    ("2025-10-27", "Bronca Yamal-Carvajal-Vinicius", "ABC Madrid",
     "(Portada dedicada a Mazón y la dana en Valencia — el Clásico NO aparece)",
     "ABC", "ABC Madrid 27/10/2025", "Portada",
     "Hemeroteca digital ABC", "Sí",
     "Hallazgo: la bronca NO llegó a portada — el día está dominado por la crisis de Mazón."),
    ("2025-10-28", "Bronca Yamal-Carvajal-Vinicius", "ABC Madrid",
     "(Portada dedicada a Extremadura adelantando elecciones — el Clásico NO aparece)",
     "ABC", "ABC Madrid 28/10/2025", "Portada",
     "Hemeroteca digital ABC", "Sí",
     "Hallazgo: tampoco llegó al martes."),

    # ============ ORIGENES (1902-1929) ============
    ("1902-05-13", "Primer Clásico", "Madrid FC vs FC Barcelona",
     "Madrid FC 1 - 3 FC Barcelona. Primer Clásico de la historia. Los catalanes, con más experiencia (3 años), ganan al recién creado Madrid FC.",
     "Wikipedia / RFEF", "—", "—",
     "Documental", "Sí (hecho histórico)",
     "Copa de la Coronación, semifinal. Hipódromo (Madrid)."),
    ("1929-02-17", "Primer Clásico de Liga", "FC Barcelona vs Real Madrid",
     "Real Madrid 2-1 FC Barcelona. Primer Clásico de la primera Liga española.",
     "Wikipedia / RFEF", "—", "—",
     "Documental", "Sí (hecho histórico)",
     "Les Corts, 2ª jornada de la 1ª Liga."),

    # ============ DI STÉFANO / KUBALA (años 50) ============
    ("1953-07-24", "Di Stéfano ficha", "Alfredo Di Stéfano",
     "Yo he venido a España para jugar en el Barcelona.",
     "Marca", "Marca 24/07/1953", "—",
     "Prensa primaria", "Parcial (no localizada en hemeroteca BNE)",
     "Acabó fichando por el Madrid. Caso histórico."),
    ("1953-10-25", "Di Stéfano vs Kubala", "Daucik (entrenador Barça)",
     "Di Stéfano es más ágil y resistente, pero no llega al nivel de Kubala en concepción del juego.",
     "Marca", "Marca octubre 1953", "—",
     "Prensa primaria", "Parcial",
     "Análisis previo al primer Di Stéfano-Kubala."),
    ("1953-10-25", "Di Stéfano vs Kubala", "Marca",
     "Kubala, el mejor interior del mundo.",
     "Marca", "Marca octubre 1953", "Titular",
     "Prensa primaria", "Parcial", ""),
    ("1953-10-25", "Di Stéfano vs Kubala", "La Vanguardia",
     "La gente solo se fija en dos hombres: Kubala y Di Stéfano.",
     "La Vanguardia", "La Vanguardia octubre 1953", "Corresponsal Madrid",
     "Prensa primaria", "Parcial", ""),
    ("1965-09-26", "Era Bernabéu presidente", "Santiago Bernabéu (presidente Madrid)",
     "El colegiado Leafe fue el mejor jugador del Barça.",
     "Memoria oral / Futbol Gate", "—", "—",
     "Documental", "Parcial",
     "Comentario sarcástico sobre arbitraje."),
    ("1965-09-26", "Era Bernabéu presidente", "Francisco Gento",
     "Se quería que otro club ganara la Copa de Europa, no siempre el mismo.",
     "Memoria oral", "—", "—",
     "Documental", "Parcial", ""),

    # ============ MARADONA (1983) ============
    ("1983-06-26", "Maradona ovacionado Bernabéu", "Diego Armando Maradona",
     "Carrasco me la dio en mitad de campo, me llevé al portero por delante y esperé a Juan José, que ya venía, y le dejé pasar. Se rompió las pelotas contra el palo y yo la empujé. Después nos cruzamos y le pedí perdón. Me mandó a la mierda.",
     "Olé (entrevista)", "Olé, años después", "—",
     "Prensa secundaria", "Sí",
     "Final Copa de la Liga ida, Bernabéu 2-2."),
    ("1983-09-24", "Goikoetxea-Maradona", "Diego Maradona",
     "Me partió el tobillo en nuestro campo, a 60 metros del arco de ellos. Nunca creí que iba a venirme a buscar con tanta mala leche. Cuando paro la pelota, siento un 'crack', como cuando se rompe una madera.",
     "Múltiples (ESPN, Vice, La Nación)", "Diversas entrevistas posteriores", "—",
     "Prensa secundaria", "Sí",
     "Fractura del maléolo peroneal."),
    ("1983-09-24", "Goikoetxea-Maradona", "César Luis Menotti (entrenador Barça)",
     "Deberá morirse alguien para que cambien las cosas.",
     "Prensa española época", "Sept 1983", "—",
     "Prensa secundaria", "Sí", ""),
    ("1983-09-24", "Goikoetxea-Maradona", "Javier Clemente (entrenador Athletic)",
     "Estoy orgulloso de mis jugadores.",
     "Prensa española época", "Sept 1983", "—",
     "Prensa secundaria", "Sí", ""),
    ("1983-09-24", "Goikoetxea-Maradona", "Andoni Goikoetxea",
     "Fue una acción más del partido, no merezco ninguna sanción. Viví lo peor y lo mejor del fútbol con solo cuatro días de diferencia, por eso las guardo (las botas).",
     "Múltiples (Panenka, ESPN)", "Posterior", "—",
     "Prensa secundaria", "Sí",
     "Sancionado con 18 partidos (rebajados a 7-10)."),

    # ============ STOICHKOV ============
    ("2003", "Stoichkov", "Hristo Stoichkov",
     "Siempre voy a odiar al Real Madrid. Es más fácil que se abra la tierra a que yo acepte trabajar en ese club. El Real Madrid me da ganas de vomitar.",
     "Múltiples (Milenio, Facebook FCBarcelonista)", "2003", "—",
     "Prensa secundaria", "Sí", ""),
    ("2000s", "Stoichkov", "Hristo Stoichkov",
     "El Madrid me da asco, nunca me veréis con una camiseta blanca.",
     "Múltiples", "—", "—",
     "Prensa secundaria", "Sí", ""),

    # ============ FIGO 2002 ============
    ("2002-11-23", "Cochinillo a Figo", "Luis Figo",
     "No me siento ni Judas ni traidor.",
     "Memorias del Fútbol / Infobae", "Posterior", "—",
     "Prensa secundaria", "Sí",
     "Lanzamientos: cabeza de cochinillo, botellas whisky, agua, móviles. Pancartas 'Judas'. 110 dB."),

    # ============ ERA MOURINHO-PEP (2010-2013) ============
    ("2011-04-26", "RP del 'puto jefe'", "Pep Guardiola",
     "Como Mou me trata de Pep, yo le voy a tratar de José. No le conozco personalmente, pero al gerente que sí le conoce, mañana a las 8.45 nos enfrentamos en el campo. Fuera del campo, él ya ha ganado todo el año. Que se lleve la Champions personal fuera del campo, se la regalo y nos vamos a casa. En esta sala (de prensa), él es el puto jefe, el puto amo. Yo no quiero competir con él aquí ni un instante.",
     "Libertad Digital, Goal, TUDN", "26/04/2011", "Bernabéu (sala de prensa)",
     "Prensa primaria contemporánea", "Sí",
     "Rueda de prensa previa Champions semifinal."),
    ("2011-04-27", "RP UNICEF Mou", "José Mourinho",
     "¿Por qué? ¿Por qué? Yo no entiendo por qué. No sé si es por la publicidad de UNICEF, no sé si son muy simpáticos. Stark, Ovrebo, De Bleeckere, Bussaca... no entiendo por qué.",
     "Libertad Digital", "27/04/2011", "Sala de prensa Bernabéu",
     "Prensa primaria contemporánea", "Sí",
     "Tras roja a Pepe en 0-2 Champions."),
    ("2011-04-27", "RP UNICEF Mou", "José Mourinho",
     "Guardiola ha ganado una Champions que a mí me daría vergüenza haber ganado.",
     "Libertad Digital", "27/04/2011", "Sala de prensa Bernabéu",
     "Prensa primaria contemporánea", "Sí", ""),
    ("2011-08-17", "Dedo en el ojo a Tito Vilanova", "José Mourinho (acción)",
     "(Mourinho mete el dedo en el ojo a Tito Vilanova, segundo de Pep, durante tangana al final del partido.)",
     "Goal, El Nacional, vídeo viral", "17/08/2011", "Camp Nou",
     "Vídeo + prensa", "Sí",
     "Sanción: 2 partidos. Imagen icónica con 'El Observador' (Francesc Satorra)."),
    ("2011-08-18", "Dedo en el ojo a Tito", "AS (titular)",
     "Mourinho le metió un dedo en el ojo a Tito Vilanova. ¿Por qué? Por Messi.",
     "AS (web)", "AS 18/08/2011", "Portada digital",
     "Wayback Machine (archive.org)", "Sí",
     "Snap 18/08/2011 20:56 UTC."),
    ("2011-08-18", "Dedo en el ojo a Tito", "Joan Gaspart (recogido por AS)",
     "Mourinho tiene una doble personalidad. Aunque en Madrid estén encantados con él, no es el Mourinho que yo conocí. Le gustaría que todo terminara con una disculpa del luso.",
     "AS (web)", "AS 18/08/2011", "Declaraciones",
     "Wayback Machine (archive.org)", "Sí",
     "Ex-presidente del Barça."),
    ("2011-08-18", "Dedo en el ojo a Tito", "Xavi Hernández (recogido por AS)",
     "Es lamentable la imagen del Madrid. No están a la altura.",
     "AS (web)", "AS 18/08/2011", "Declaraciones",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2011-08-18", "Dedo en el ojo a Tito", "Gerard Piqué (recogido por AS)",
     "Mourinho se está cargando el fútbol español.",
     "AS (web)", "AS 18/08/2011", "Declaraciones",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2011-08-18", "Dedo en el ojo a Tito", "Joaquim Villarrubí (vicepresidente FC Barcelona)",
     "Mourinho es una lacra para el fútbol. Fue el entrenador del Real Madrid quien obligó a sus jugadores a abandonar el campo cuando los jugadores del Barcelona recogían la Supercopa.",
     "AS (web)", "AS 18/08/2011", "Declaraciones",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2011-08-18", "Dedo en el ojo a Tito", "AS (identificación 'tío del bigote')",
     "Se llama Francesc Satorra y es el encargado del túnel de vestuarios del Camp Nou. Ayer vio cómo Mourinho le metía un dedo en el ojo a Tito Vilanova y hoy en internet ya se venden camisetas con su cara.",
     "AS (web)", "AS 18/08/2011", "Crónica",
     "Wayback Machine (archive.org)", "Sí",
     "Identifica al fotógrafo viral del momento."),
    ("2011-08-18", "Dedo en el ojo a Tito", "Marca (titular crónica)",
     "El Barcelona se lleva la Supercopa tras derrotar a un buen Real Madrid en un partidazo que acabó de forma vergonzosa.",
     "Marca (web)", "Marca 18/08/2011", "Portada digital",
     "Wayback Machine (archive.org)", "Sí",
     "Snap 18/08/2011 01:34 UTC."),
    ("2011-08-18", "Dedo en el ojo a Tito", "José Mourinho (a Marca)",
     "De 'Pito' o como se llame no tengo nada que ocultar.",
     "Marca (web)", "Marca 18/08/2011", "RP post-partido",
     "Wayback Machine (archive.org)", "Sí",
     "Mourinho niega haber metido el dedo en el ojo a Tito Vilanova, vacilando con su nombre."),
    ("2011-08-18", "Dedo en el ojo a Tito", "Pep Guardiola (a Marca)",
     "Cuidado, porque un día nos haremos daño. Las imágenes hablan por sí solas.",
     "Marca (web)", "Marca 18/08/2011", "RP post-partido",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2011-08-18", "Dedo en el ojo a Tito", "Pep Guardiola (a Mundo Deportivo)",
     "Un día pasará algo grave. Tenemos que andar con cuidado. Estas cosas no se deben hacer.",
     "Mundo Deportivo (web)", "MD 18/08/2011", "RP post-partido",
     "Wayback Machine (archive.org)", "Sí",
     "Sobre la agresión de Mourinho a Tito."),
    ("2011-08-18", "Dedo en el ojo a Tito", "Iker Casillas (a Marca)",
     "Una entrada, al suelo y lo de siempre.",
     "Marca (web)", "Marca 18/08/2011", "RP post-partido",
     "Wayback Machine (archive.org)", "Sí",
     "Capitán del Madrid sobre la tangana."),
    ("2011-08-18", "Dedo en el ojo a Tito", "Gerard Piqué (a Marca)",
     "Espero no se hable de la tangana, es una pena, no es la primera vez y siempre son los mismos. Alguien tiene que tomar cartas en el asunto. Mourinho está destrozando el fútbol español. Hablan mucho de los catalanes, pero el problema lo tienen en Madrid.",
     "Marca (web)", "Marca 18/08/2011", "Sala mixta",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2011-08-18", "Dedo en el ojo a Tito", "Gerard Piqué (a Mundo Deportivo)",
     "Están haciendo cosas que no son propias de personas.",
     "Mundo Deportivo (web)", "MD 18/08/2011", "Sala mixta",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2011-08-18", "Dedo en el ojo a Tito", "Mundo Deportivo (titular)",
     "Los buenos siempre ganan. Un buen Madrid que ha acabado recurriendo a la violencia como única arma para frenar a los cracks barcelonistas.",
     "Mundo Deportivo (web)", "MD 18/08/2011", "Portada digital",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2011-08-18", "Dedo en el ojo a Tito", "José Mourinho (a El País)",
     "El fútbol es para hombres.",
     "El País (web)", "El País 18/08/2011", "Crónica de Nadia Tronchoni",
     "Wayback Machine (archive.org)", "Sí",
     "Frase tras la agresión a Tito Vilanova."),
    ("2011-08-18", "Dedo en el ojo a Tito", "El País (José Sámano)",
     "Messi sí que es único. El Madrid no puede con el argentino, el mayor castigo de su historia y artífice del triunfo del Barcelona en una Supercopa intensa.",
     "El País (web)", "El País 18/08/2011", "Crónica",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2011-08-18", "Dedo en el ojo a Tito", "El País (datos)",
     "El discípulo ya iguala al maestro: con la Supercopa conquistada ayer, Guardiola alcanza el número de trofeos (11) alzados durante los ocho años de Cruyff en el banquillo.",
     "El País (web)", "El País 18/08/2011", "Sección Deportes",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2011-08-19", "Dedo en el ojo a Tito", "Marca (titular)",
     "Que sea la última vez.",
     "Marca (web)", "Marca 19/08/2011", "Portada digital",
     "Wayback Machine (archive.org)", "Sí",
     "Snap 19/08/2011 08:22 UTC."),
    ("2011-08-19", "Dedo en el ojo a Tito", "Marca (editorial)",
     "Esto se tiene que acabar. Real Madrid y Barcelona no pueden salir a tangana por partido.",
     "Marca (web)", "Marca 19/08/2011", "Editorial",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2011-08-19", "Dedo en el ojo a Tito", "Real Madrid (vestuario, anónimo)",
     "Jugando así lo normal es que les ganemos.",
     "Marca (web)", "Marca 19/08/2011", "Sergio Fernández",
     "Wayback Machine (archive.org)", "Sí",
     "Valoración interna del vestuario blanco a pesar de la derrota."),
    ("2011-08-19", "Dedo en el ojo a Tito", "Rafael Nadal (desde Cincinnati)",
     "Hay cosas más importantes que ganar o perder.",
     "Marca (web)", "Marca 19/08/2011", "Declaraciones",
     "Wayback Machine (archive.org)", "Sí",
     "Nadal sobre los incidentes de la Supercopa."),
    ("2011-08-19", "Dedo en el ojo a Tito", "Marca (blog 'Tirando a dar')",
     "Mourinho eclipsa al Papa. ¿Qué pretende el entrenador y su propio club? ¿Tratar de que nadie se de cuenta de que el archirrival les venció?",
     "Marca (web)", "Marca 19/08/2011", "Blog 'Tirando a dar'",
     "Wayback Machine (archive.org)", "Sí",
     "El día de la JMJ, el dedo en el ojo eclipsa al Papa en los medios."),
    ("2015-11-22", "Iniesta ovación Bernabéu", "AS (titular hoy)",
     "Goleada al Florentinato.",
     "AS (web)", "AS 22/11/2015", "Portada digital",
     "Wayback Machine (archive.org)", "Sí",
     "Madrid 0 - 4 Barça."),
    ("2015-11-22", "Iniesta ovación Bernabéu", "AS (titular crónica)",
     "Uno a uno del Madrid: desastre general y naufragio de la BBC.",
     "AS (web)", "AS 22/11/2015", "Sección Madrid",
     "Wayback Machine (archive.org)", "Sí",
     "Crítica al tridente Bale-Benzema-Cristiano."),
    ("2015-11-22", "Iniesta ovación Bernabéu", "Mundo Deportivo (titular)",
     "Sinfonía espectacular del Barça y concierto de pitos para el Real Madrid. El equipo de Luis Enrique degradó al equipo blanco, muy vulgar en su juego, hasta el ridículo en el Bernabéu y provocó gritos de 'Florentino, dimisión'.",
     "Mundo Deportivo (web)", "MD 22/11/2015", "Portada digital",
     "Wayback Machine (archive.org)", "Sí",
     "Snap MD 22/11/2015 14:31 UTC."),
    ("2015-11-22", "Iniesta ovación Bernabéu", "Mundo Deportivo (revista de prensa)",
     "La prensa mundial se rinde al Barça. La prensa internacional habla de 'Real Barça' y define como 'exhibición' el partido realizado por los de Luis Enrique.",
     "Mundo Deportivo (web)", "MD 22/11/2015", "Revista de prensa",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2015-11-22", "Iniesta ovación Bernabéu", "Cristiano Ronaldo (vía La Gazzetta dello Sport)",
     "O Benítez o yo.",
     "La Gazzetta / Mundo Deportivo", "MD 22/11/2015", "Top Secret",
     "Wayback Machine (archive.org)", "Sí",
     "Cristiano habría pedido la destitución de Benítez tras el 0-4."),
    ("2015-11-22", "Iniesta ovación Bernabéu", "Rivaldo",
     "El ex azulgrana le aconseja al Madrid que Zidane ocupe el lugar de Rafa Benítez en el banquillo blanco.",
     "Mundo Deportivo (web)", "MD 22/11/2015", "Declaraciones",
     "Wayback Machine (archive.org)", "Sí",
     "Rivaldo predice la sustitución de Benítez por Zidane."),
    ("2015-11-22", "Iniesta ovación Bernabéu", "Marcelo (anécdota)",
     "Marcelo pierde los papeles y llama 'tonto' a un periodista.",
     "Mundo Deportivo (web)", "MD 22/11/2015", "Crónica",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2015-11-19", "Previa 0-4 Bernabéu 2015", "Andrés Iniesta (RP previa)",
     "El Clásico me pone como una moto. Cada uno le pone al partido el calificativo que quiere, ojalá me siga poniendo como una moto.",
     "Marca (web)", "Marca 19/11/2015", "Por S. Font, Barcelona",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2015-11-19", "Previa 0-4 Bernabéu 2015", "Manolo Sanchís",
     "La continuidad de Benítez no pasa por este partido.",
     "Marca (web)", "Marca 19/11/2015", "Videoblog",
     "Wayback Machine (archive.org)", "Sí",
     "Aunque cree que perder sería un drama."),
    ("2015-11-23", "Iniesta ovación Bernabéu", "AS (titular hoy)",
     "Florentino segundo frente.",
     "AS (web)", "AS 23/11/2015", "Portada digital",
     "Wayback Machine (archive.org)", "Sí",
     "Snap AS 23/11/2015 14:42 UTC."),
    ("2015-11-23", "Iniesta ovación Bernabéu", "Dani Alves (a AS)",
     "Al Real Madrid que le vaya mal, no, lo siguiente.",
     "AS (web)", "AS 23/11/2015", "Sección Barcelona",
     "Wayback Machine (archive.org)", "Sí",
     "Por Moisés Llorens."),
    ("2015-11-23", "Iniesta ovación Bernabéu", "Dani Alves (a Mundo Deportivo)",
     "El problema de Cristiano es querer ser demasiado protagonista. El secreto del Barça para ganar al Madrid y no debilitarse es no tener ego.",
     "Mundo Deportivo (web)", "MD 23/11/2015", "Declaraciones",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2015-11-23", "Iniesta ovación Bernabéu", "Florentino Pérez (RP de defensa de Benítez)",
     "Yo no sé lo que pasará en seis meses. Hay una campaña contra mí. El equipo lleva desde enero viviendo un desgaste.",
     "Mundo Deportivo (web)", "MD 23/11/2015", "RP Florentino",
     "Wayback Machine (archive.org)", "Sí",
     "Florentino ratifica a Rafa Benítez tras el 0-4 y culpa a Ancelotti."),
    ("2015-11-23", "Iniesta ovación Bernabéu", "Ramón Calderón (sobre Florentino)",
     "¡Qué poca vergüenza! Hablar de campaña contra él, quien ha contratado a dos periodistas condenados por delitos de calumnias contra mí.",
     "Mundo Deportivo (web)", "MD 23/11/2015", "Twitter",
     "Wayback Machine (archive.org)", "Sí",
     "Ex-presidente del Madrid sobre Florentino."),
    ("2015-11-23", "Iniesta ovación Bernabéu", "Jugador del Madrid (anónimo, top secret)",
     "Cristiano Ronaldo quiere irse. No es bueno el ambiente en el vestuario.",
     "Mundo Deportivo (web)", "MD 23/11/2015", "Top Secret",
     "Wayback Machine (archive.org)", "Sí",
     "Mensaje WhatsApp de un jugador del Madrid a un compañero de Brasil del Barça tras el 0-4."),
    ("2025-10-27", "Bronca Yamal-Carvajal-Vinicius", "AS (titular hoy)",
     "Rompe récords de Lamine. ¿Debe sancionar el Madrid a Vinicius? ¿Tiene que renovar o salir?",
     "AS (web)", "AS 27/10/2025", "Portada digital",
     "Wayback Machine (archive.org)", "Sí",
     "Snap AS 27/10/2025 16:55 UTC."),
    ("2025-10-27", "Bronca Yamal-Carvajal-Vinicius", "Vinicius Junior (a Lamine Yamal)",
     "Llorón, no me toques.",
     "AS (web)", "AS 27/10/2025", "Vídeo del partido",
     "Wayback Machine (archive.org)", "Sí",
     "Cita literal de Vini hacia Yamal en la tangana."),
    ("2025-10-27", "Bronca Yamal-Carvajal-Vinicius", "AS (titular sobre Vinicius)",
     "Vinicius valora la opción de salir si todo sigue igual. Vinicius siente que ha cumplido con su parte, pero no se está respetando su estatus. La opción de marcharse se valora seriamente.",
     "AS (web)", "AS 27/10/2025", "Marco Ruiz",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2025-10-27", "Bronca Yamal-Carvajal-Vinicius", "AS (debate de usuarios)",
     "El 'vámonos fuera' de Lamine a Carvajal es un gesto de soberbia.",
     "AS (web)", "AS 27/10/2025", "El debate de los usuarios",
     "Wayback Machine (archive.org)", "Sí",
     "Frase del día tras la bronca."),
    ("2025-10-28", "Bronca Yamal-Carvajal-Vinicius", "AS (titular crónica)",
     "Marcó Bellingham y Vinicius no pudo contenerse: el gesto del que pocos se percataron.",
     "AS (web)", "AS 28/10/2025", "AStv",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2025-10-28", "Bronca Yamal-Carvajal-Vinicius", "AS (Sergio López)",
     "El 'Caso Vinicius' se expande.",
     "AS (web)", "AS 28/10/2025", "Sección Madrid",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2025-10-27", "Bronca Yamal-Carvajal-Vinicius", "El País (Lorenzo Calonge)",
     "La victoria en el clásico refuerza a Xabi Alonso, que afronta el mayor desafío de Vinicius a su autoridad. El necesitado triunfo blanco impulsa el proyecto del técnico, que debe gestionar el desaire más grave del brasileño dentro de un vestuario con más de un morro torcido.",
     "El País (web)", "El País 27/10/2025", "Crónica El Clásico",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2025-10-26", "Bronca Yamal-Carvajal-Vinicius", "Xabi Alonso (a El País)",
     "El equipo necesitaba la sensación de ganar un partido grande.",
     "El País (web)", "El País 26/10/2025", "RP post-partido",
     "Wayback Machine (archive.org)", "Sí",
     "Por Lorenzo Calonge. Xabi anuncia que hablará por supuesto con Vinicius."),
    ("2025-10-26", "Bronca Yamal-Carvajal-Vinicius", "El País (David Álvarez)",
     "El Madrid reconquista el clásico. Tras cuatro derrotas seguidas, el equipo de Xabi Alonso arrolla a un Barça mermado por las bajas y con Lamine Yamal desaparecido con un partido de gran intensidad en el que volvió a brillar Bellingham y se distancia cinco puntos en cabeza.",
     "El País (web)", "El País 26/10/2025", "Crónica",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2025-10-26", "Bronca Yamal-Carvajal-Vinicius", "Markus Sorg (2º entrenador del Barça)",
     "Lamine está aprendiendo, le ayudaremos.",
     "El País (web)", "El País 26/10/2025", "RP post-partido",
     "Wayback Machine (archive.org)", "Sí",
     "Yamal estuvo en el foco, abucheado por el Bernabéu y enfrentado a Carvajal y Vinicius."),
    ("2025-10-27", "Bronca Yamal-Carvajal-Vinicius", "El País (Manuel Jabois opinión)",
     "Este infernal y precioso olor al viejo Clásico de siempre.",
     "El País (web)", "El País 27/10/2025", "Opinión",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2025-10-28", "Bronca Yamal-Carvajal-Vinicius", "El País (Daniel Verdú, París)",
     "Lamine, algo tan grave.",
     "El País (web)", "El País 28/10/2025", "Opinión desde París",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2025-10-28", "Bronca Yamal-Carvajal-Vinicius", "El País (Juan I. Irigoyen)",
     "Los dilemas de Flick en su segundo año en el Barcelona. La política del club y la gestión de Lamine preocupan a un técnico sin respuestas tácticas.",
     "El País (web)", "El País 28/10/2025", "Sección Barcelona",
     "Wayback Machine (archive.org)", "Sí", ""),
    ("2025-10-27", "Bronca Yamal-Carvajal-Vinicius", "Marca (titular hoy)",
     "El Real Madrid se escapa.",
     "Marca (web)", "Marca 27/10/2025", "Portada digital",
     "Wayback Machine (archive.org)", "Sí",
     "Snap Marca 27/10/2025 17:12 UTC."),
    ("2025-10-28", "Bronca Yamal-Carvajal-Vinicius", "Marca (titular hoy)",
     "El Madrid quiere la fiesta en paz.",
     "Marca (web)", "Marca 28/10/2025", "Portada digital",
     "Wayback Machine (archive.org)", "Sí",
     "Snap Marca 28/10/2025 18:52 UTC."),
    ("2011-04-25", "Pre-Clásico Champions", "Andrés Iniesta (RP previa)",
     "Todos conocemos a Guardiola. Yo no creo que quisiera decir eso. El máster no busca excusas.",
     "Marca (web)", "Marca 25/04/2011", "RP previa",
     "Wayback Machine (archive.org)", "Sí",
     "Defensa pública del Pep tras críticas de Mou."),
    ("2011-04-25", "Pre-Clásico Champions", "Johan Cruyff (a El Periódico)",
     "Más que temer quién pitará o si el césped estará alto, preocúpate de tu equipo. El Madrid llega más fuerte.",
     "El Periódico (vía Marca)", "El Periódico 25/04/2011", "Columna",
     "Wayback Machine (archive.org)", "Sí",
     "Recadito de Cruyff a Pep."),
    ("2011-04-25", "Pre-Clásico Champions", "Víctor Valdés (RP previa)",
     "Dependerá del árbitro que podamos hacer nuestro juego. No hay que obsesionarse con estas cosas. Tenemos que ir a lo nuestro y hacer el partido que nos interesa.",
     "Mundo Deportivo (web)", "MD 25/04/2011", "RP previa",
     "Wayback Machine (archive.org)", "Sí",
     "Snap MD 25/04/2011 08:55 UTC."),
    ("Posterior", "Dedo en el ojo a Tito Vilanova", "José Mourinho",
     "Fallé. (Tras la muerte de Vilanova)",
     "El Nacional", "—", "—",
     "Prensa secundaria", "Sí", ""),
    ("2020-12", "Casillas-Mourinho topo", "Iker Casillas",
     "Asumí que yo era el topo.",
     "Infobae, El Español, Libertad Digital", "Documental 2020", "—",
     "Prensa primaria contemporánea", "Sí",
     "Reconciliación posterior."),
    ("2020-12", "Casillas-Mourinho topo", "Antón Meana (Cadena SER)",
     "Topo ninguno. Había filtraciones y alguna filtración salía permanentemente del cuerpo técnico de Mourinho.",
     "Defensa Central", "2020", "—",
     "Prensa primaria contemporánea", "Sí", ""),
    ("2025-10-23", "Casillas-Mourinho posterior", "Iker Casillas",
     "La gente se queda con el odio (hate), pero con el tiempo todo cambia.",
     "Infobae", "23/10/2025", "—",
     "Prensa primaria", "Sí", ""),

    # ============ INIESTA / OVACIÓN BERNABEU 2015 ============
    ("2015-11-21", "Iniesta ovación Bernabéu", "Andrés Iniesta",
     "Quiero agradecer a los fans. Nos sentimos muy bien, jugamos un partido completo en todos los sentidos. Les dimos pocas opciones, apenas perdimos el balón.",
     "Sphera Sports, Tribuna, Goal", "21/11/2015", "Bernabéu",
     "Prensa primaria contemporánea", "Sí",
     "Madrid 0-4 Barça."),
    ("2015-11-21", "Iniesta ovación Bernabéu", "Luis Enrique (entrenador Barça)",
     "Andrés Iniesta es patrimonio de la humanidad, no sólo de los culés.",
     "Sphera Sports, beIN", "21/11/2015", "—",
     "Prensa primaria contemporánea", "Sí", ""),

    # ============ PIQUÉ vs RAMOS 2017 ============
    ("2017-04-23", "Ramos-Piqué", "Sergio Ramos",
     "¡Habla ahora, habla ahora!",
     "Líbero, Goal", "23/04/2017", "Bernabéu",
     "Vídeo + prensa", "Sí",
     "Tras roja a Ramos, señalando a la grada hacia Piqué."),
    ("2017", "Ramos-Piqué", "Gerard Piqué",
     "Desde el palco del Bernabéu se mueven los hilos del país. Se va a arrepentir cuando llegue a casa. Mi relación con él (Ramos) no es muy buena, pero está mejorando.",
     "Goal, Líbero", "Abril 2017", "Twitter / RP",
     "Prensa primaria contemporánea", "Sí", ""),
    ("Posterior", "Pepe-Piqué", "Gerard Piqué",
     "Una escena monumental. Ver esa roja [a Pepe] fue uno de los mayores placeres que he tenido en mi vida.",
     "Goal", "Posterior", "—",
     "Prensa secundaria", "Sí", ""),

    # ============ 2-6 (2009) PUYOL ============
    ("2009-05-02", "2-6 Pep primer año", "Carles Puyol",
     "(Celebra besando el brazalete de capitán con la bandera catalana ante la afición del Bernabéu.)",
     "Bleacher Report", "2009", "Bernabéu",
     "Vídeo histórico", "Sí",
     "Madrid 2-6 Barça."),
    ("2025", "Puyol Clásicos Leyendas", "Carles Puyol",
     "Un clásico siempre es un clásico. Todos quieren ganar.",
     "Infobae", "2025", "Costa Rica (Clásico Leyendas)",
     "Prensa primaria contemporánea", "Sí", ""),

    # ============ CRISTIANO vs MESSI ============
    ("2022-2024", "Cristiano vs Messi", "Cristiano Ronaldo",
     "¿Messi es mejor que yo? No estoy de acuerdo. No quiero ser humilde.",
     "Piers Morgan / La Nación", "Entrevistas múltiples", "—",
     "Prensa primaria contemporánea", "Sí", ""),
    ("2022-2024", "Cristiano vs Messi", "Cristiano Ronaldo",
     "Nos respetamos mucho. No somos amigos, pero compartimos 15 años en el stage de los premios y siempre nos llevamos muy bien. La prensa siempre quiso vender que éramos enemigos, pero no es cierto.",
     "Múltiples", "—", "—",
     "Prensa primaria contemporánea", "Sí", ""),
    ("2023", "Messi sobre Cristiano", "Lionel Messi",
     "Una batalla, entre comillas. (Sobre los Clásicos)",
     "L'Équipe (tras Balón de Oro)", "2023", "—",
     "Prensa primaria contemporánea", "Sí", ""),

    # ============ LAMINE YAMAL ============
    ("2025-03", "Lamine Yamal", "Lamine Yamal",
     "El Madrid es el rival a batir.",
     "AS", "Marzo 2025", "—",
     "Prensa primaria contemporánea", "Sí", ""),
    ("2025-10", "Lamine Yamal", "Lamine Yamal",
     "Roban, se quejan… (sobre el Madrid en transmisión Kings League con Ibai)",
     "Múltiples (Infobae, Eurosport)", "Octubre 2025", "—",
     "Stream + prensa", "Sí", ""),
    ("2025-10-26", "Bronca Yamal-Carvajal", "Vinicius Junior",
     "Solo das pases atrás, solo das pases atrás. Tú hablas mucho, habla ahora.",
     "Infobae, Eurosport, SDP Noticias", "Tras Madrid 2-1 Barça", "Bernabéu",
     "Vídeo + prensa", "Sí",
     "Eco directo al 'habla ahora' de Sergio Ramos a Piqué de 2017."),
    ("2025-10-26", "Bronca Yamal-Carvajal", "Dani Carvajal (capitán Madrid)",
     "Tú hablas mucho. Tú hablas mucho.",
     "Infobae, Eurosport", "Tras Madrid 2-1 Barça", "Bernabéu",
     "Vídeo + prensa", "Sí", ""),

    # ============ EL CHIRINGUITO ============
    ("2010s-2020s", "El Chiringuito", "Tomás Roncero",
     "Porque el coronavirus no me deja, pero me lanzaba a darte un abrazo ahora mismo.",
     "Diez Minutos / El Chiringuito", "—", "—",
     "Vídeo TV", "Sí", ""),
    ("2010s-2020s", "El Chiringuito", "Josep Pedrerol",
     "El ADN del Madrid es la leche. Cuando damos al Madrid por perdido, gana títulos.",
     "El Chiringuito", "—", "—",
     "Vídeo TV", "Sí", ""),
    ("2010s-2020s", "El Chiringuito", "Edu Aguirre",
     "Messi es un 7 en todo, pero no es un 10 en nada.",
     "El Nacional", "—", "—",
     "Vídeo TV", "Sí", ""),

    # ============ NO VERIFICADAS ============
    ("?", "Cruyff (atribución dudosa)", "Johan Cruyff",
     "Preferiría perder un Clásico que un partido cualquiera.",
     "Frases de Futbolistas (sin fuente primaria)", "—", "—",
     "Atribuida", "NO — posiblemente apócrifa", "No localizada en fuentes primarias."),
    ("?", "Cristiano Ronaldo (atribución dudosa)", "Cristiano Ronaldo",
     "Siempre intento cuidar mi cuerpo, la comida y dormir, que es muy importante.",
     "frasesdefutbolistas.com", "—", "—",
     "Atribuida", "NO — sin fuente primaria",
     "Coherente con su discurso pero atribución exacta no localizada."),
]

# ============================================================================
# GENERACIÓN DEL EXCEL
# ============================================================================

wb = Workbook()
wb.remove(wb.active)  # Quitamos hoja por defecto

# Separamos en dos hojas según tipo de fuente
def is_primary_archive(r):
    t = r[7]
    return "Hemeroteca digital" in t or "Wayback" in t

ROWS_HEMERO = [r for r in ROWS if is_primary_archive(r)]
ROWS_OTROS = [r for r in ROWS if not is_primary_archive(r)]


def fill_sheet(ws, rows):
    HEADERS = ["Fecha", "Era / contexto", "Protagonista", "Cita literal",
               "Fuente", "Edición / publicación", "Página / lugar",
               "Tipo fuente", "Verificado", "Notas"]

    header_font = Font(bold=True, color="FFFFFF", size=12)
    header_fill = PatternFill("solid", fgColor="1F4E78")
    header_align = Alignment(horizontal="center", vertical="center", wrap_text=True)

    verified_fill = PatternFill("solid", fgColor="D5E8D4")
    partial_fill = PatternFill("solid", fgColor="FFF2CC")
    unverified_fill = PatternFill("solid", fgColor="F8CECC")

    thin_border = Border(
        left=Side(style="thin", color="CCCCCC"),
        right=Side(style="thin", color="CCCCCC"),
        top=Side(style="thin", color="CCCCCC"),
        bottom=Side(style="thin", color="CCCCCC"),
    )

    for col, header in enumerate(HEADERS, 1):
        cell = ws.cell(row=1, column=col, value=header)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = header_align
        cell.border = thin_border

    for ri, row in enumerate(rows, 2):
        for ci, value in enumerate(row, 1):
            cell = ws.cell(row=ri, column=ci, value=value)
            cell.alignment = Alignment(vertical="top", wrap_text=True)
            cell.border = thin_border

        verified = row[8].lower() if len(row) > 8 else ""
        if verified.startswith("sí"):
            ws.cell(row=ri, column=9).fill = verified_fill
        elif verified.startswith("parcial"):
            ws.cell(row=ri, column=9).fill = partial_fill
        elif verified.startswith("no"):
            ws.cell(row=ri, column=9).fill = unverified_fill

    widths = [12, 24, 28, 80, 20, 30, 22, 22, 14, 40]
    for i, w in enumerate(widths, 1):
        ws.column_dimensions[get_column_letter(i)].width = w

    ws.row_dimensions[1].height = 32
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = ws.dimensions


# Pestaña 1 — fuentes primarias verificadas (hemeroteca ABC + Wayback Machine)
ws1 = wb.create_sheet("Archivos primarios verificados")
fill_sheet(ws1, ROWS_HEMERO)

# Pestaña 2 — el resto de declaraciones (prensa primaria web, libros, vídeo, etc.)
ws2 = wb.create_sheet("Otras citas")
fill_sheet(ws2, ROWS_OTROS)

# Guardar
out = Path(__file__).resolve().parents[1] / "docs" / "clasico-declaraciones.xlsx"
out.parent.mkdir(exist_ok=True)
wb.save(out)
print(f"Generado: {out}")
print(f"  Hoja 1 (hemeroteca verificadas): {len(ROWS_HEMERO)} filas")
print(f"  Hoja 2 (otras citas): {len(ROWS_OTROS)} filas")
print(f"  Total: {len(ROWS)}")

